SELECT E.EMP_NAME, E.EMP_NO, D.DEPT_TITLE, A.JOB_NAME
FROM EMPLOYEE E
JOIN DEPARTMENT D
ON(E.DEPT_CODE=D.DEPT_ID)
JOIN JOB A
ON(E.JOB_CODE= A.JOB_CODE)
WHERE EMP_NO LIKE '7_____-2%' AND
EMP_NAME LIKE '전%'
;



SELECT EMP_NAME, EMP_ID, DEPARTMENT.DEPT_TITLE
FROM EMPLOYEE
JOIN DEPARTMENT
ON (DEPARTMENT.DEPT_ID=EMPLOYEE.DEPT_CODE)
WHERE EMP_NAME LIKE '%형%';
--


SELECT EMPLOYEE.EMP_NAME "사원명",
JOB.JOB_NAME "직급명",
EMPLOYEE.DEPT_CODE "부서코드", 
DEPARTMENT.DEPT_TITLE "부서명"
FROM EMPLOYEE
JOIN DEPARTMENT
ON(EMPLOYEE.DEPT_CODE=DEPARTMENT.DEPT_ID)
JOIN JOB 
ON(JOB.JOB_CODE=EMPLOYEE.JOB_CODE)
WHERE DEPARTMENT.DEPT_TITLE LIKE '해외영업%';



SELECT E.EMP_NAME, E.BONUS, D.DEPT_TITLE, L.LOCAL_NAME
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D
ON(E.DEPT_CODE=D.DEPT_ID)
LEFT JOIN LOCATION L
ON(D.LOCATION_ID=L.LOCAL_CODE)
WHERE E.BONUS>0;



SELECT E.EMP_NAME "사원명",
A.JOB_NAME "직급명",
D.DEPT_TITLE "부서명",
L.LOCAL_NAME "근무지역명"
FROM EMPLOYEE E
JOIN DEPARTMENT D
ON(E.DEPT_CODE=D.DEPT_ID)
JOIN JOB A
ON(A.JOB_CODE=E.JOB_CODE)
JOIN LOCATION L
ON(D.LOCATION_ID = L.LOCAL_CODE)
WHERE D.DEPT_ID LIKE 'D2';

SELECT 
E.EMP_NAME "사원명",
D.DEPT_TITLE "부서명",
L.LOCAL_NAME "지역명",
N.NATIONAL_NAME "국가명"
FROM EMPLOYEE E
JOIN DEPARTMENT D
ON(E.DEPT_CODE=D.DEPT_ID)
JOIN LOCATION L
ON(L.LOCAL_CODE=D.LOCATION_ID)
JOIN NATIONAL N
ON(L.NATIONAL_CODE=N.NATIONAL_CODE ) 
WHERE L.NATIONAL_CODE IN ('KO','JP');



SELECT E.EMP_NAME,
D.DEPT_TITLE,
A.EMP_NAME
FROM EMPLOYEE E
JOIN DEPARTMENT D
ON(E.DEPT_CODE=D.DEPT_ID)
JOIN EMPLOYEE A
ON(D.DEPT_ID= A.DEPT_CODE)
WHERE A.EMP_NAME!=E.EMP_NAME;


SELECT 
E.EMP_NAME "사원명",
J.JOB_NAME "직급명",
E.SALARY "급여"
FROM EMPLOYEE E
JOIN JOB J
ON (E.JOB_CODE=J.JOB_CODE)
WHERE E.BONUS IS NULL AND
J.JOB_NAME IN ('차장','사원');

