-- UNION : 중복된 데이터 제거, 첫번째 컬럼 오름차순으로 정렬 (12명)
-- UNION ALL : 중복된데이터 제거X/ 정렬 X (14명)
--INTERSECT : 중족된 데이터만 출력 (2명)
SELECT EMP_ID, EMP_NAME, DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE DEPT_CODE='D5'
--UNION
--UNION ALL
INTERSECT
SELECT EMP_ID, EMP_NAME, DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE SALARY>3000000;


-- SUBQUERY
-- 1 단일행 (ONE ROW / ONE COLUMN)
SELECT * FROM EMPLOYEE
WHERE SALARY>=(SELECT AVG(SALARY) FROM EMPLOYEE);

-- 윤은해랑 같은 월급의 사원 선택
SELECT EMP_ID, EMP_NAME, SALARY
FROM EMPLOYEE
WHERE SALARY=(SELECT SALARY FROM EMPLOYEE
WHERE EMP_NAME='윤은해') AND EMP_NAME!= '윤은해';

-- 월급이 가장 낮거나 가장 높은 두 사람 선택
SELECT E.EMP_ID, E.SALARY, J.JOB_NAME
FROM EMPLOYEE E
JOIN JOB J
ON (E.JOB_CODE=J.JOB_CODE)
WHERE E.SALARY IN 
((SELECT MAX(SALARY) FROM EMPLOYEE),
(SELECT MIN(SALARY) FROM EMPLOYEE) );

-- D5부서 평균급여보다 급여가 높은 D1, D2 부서의 사원 
SELECT DEPT_CODE, EMP_ID, EMP_NAME, SALARY
FROM EMPLOYEE
WHERE DEPT_CODE IN ('D1', 'D2') AND SALARY >= 
(SELECT AVG(SALARY)FROM EMPLOYEE WHERE DEPT_CODE='D5' );


-- 2 다중행 (SEVERAL ROW/ ONE COLUMN)
-- IN/NOT IN, ANY, ALL, EXIST
--송중기, 박나라가 속한 부서 직원들 선택
SELECT EMP_NAME, DEPT_CODE, SALARY 
FROM EMPLOYEE
WHERE DEPT_CODE IN (SELECT DEPT_CODE FROM EMPLOYEE WHERE EMP_NAME IN ('송종기','박나라'))
;

--ANY (OR)
--ANY > X / ANY < X / ANY = X (하나의 값과 일치)
SELECT SALARY FROM EMPLOYEE 
WHERE SALARY > ANY(3000000, 2000000);

SELECT * FROM EMPLOYEE 
WHERE SALARY > 
ANY(SELECT MIN(SALARY) FROM EMPLOYEE 
WHERE DEPT_CODE IN ('D1', 'D5'));

--ALL (AND)
-- X > ALL / X < ALL / X = ALL (ALL 조회 결과가 여럿이면 에러);
SELECT SALARY FROM EMPLOYEE
WHERE SALARY > ALL(2000000, 3000000);

-- 퇴사한 직원(1명)과 같은 직급, 같은 부서 직원 출력;
SELECT E.EMP_NAME, J.JOB_NAME, D.DEPT_TITLE
FROM EMPLOYEE E
JOIN JOB J
ON(E.JOB_CODE=J.JOB_CODE)
JOIN DEPARTMENT D
ON(E.DEPT_CODE=D.DEPT_ID) 
WHERE(E.DEPT_CODE , E.JOB_CODE) IN
( SELECT DEPT_CODE, JOB_CODE FROM EMPLOYEE
WHERE ENT_YN = 'Y'
);

-- 각 부서별 가장 낮은 월급 받는 사원 출력;
SELECT SALARY FROM EMPLOYEE
WHERE (JOB_CODE, SALARY)
IN (SELECT JOB_CODE, MIN(SALARY) FROM EMPLOYEE GROUP BY JOB_CODE);


SELECT E.EMP_NAME, E.DEPT_CODE, D.DEPT_TITLE , E.SALARY
FROM EMPLOYEE E
JOIN DEPARTMENT D
ON(E.DEPT_CODE=D.DEPT_ID)
WHERE(D.DEPT_TITLE IN ('인사관리부','마케팅부','회계관리부') );
