create user kh identified by kh;
grant resource,connect to kh;


--select EMP_NAME, DEPT_CODE, DEPT_TITLE 
--from EMPLOYEE E
--LEFT JOIN DEPARTMENT D ON (E.DEPT_CODE=D.DEPT_ID);
----ON (DEPT_CODE = DEFT_ID);

--select E1.EMP_NAME 사원명, E1.EMP_ID 사번, NVL(E2.EMP_NAME, '관리가 안됨') 매니저이름
--, 1 MANAGER_ID
----from EMPLOYEE E1 
----LEFT JOIN EMPLOYEE E2 ON (E1.MANAGER_ID = E2.EMP_ID);
--
--
--
----SELECT E.EMP_NAME, E.DEPT_CODE, D.DEPT_ID, E.JOB_CODE 
----FROM EMPLOYEE E
----FULL JOIN DEPARTMENT D ON (E.DEPT_CODE = D.DEPT_ID);
--
--
--SELECT E.EMP_NAME, D.DEPT_TITLE, JOB_NAME
--FROM EMPLOYEE E
--JOIN DEPARTMENT D
--ON (E.DEPT_CODE = D.DEPT_ID)
--JOIN JOB J
--ON(J.JOB_CODE = E.JOB_CODE);
----ON (D.DEPT_ID, = J. );
--
--
--
--
--SELECT EMP_NAME, DEPT_CODE, D.DEPT_TITLE, L.NATIONAL_CODE
--FROM EMPLOYEE E
--JOIN DEPARTMENT D ON (E.DEPT_CODE= D.DEPT_ID)
--JOIN LOCATION L ON (D.LOCATION_ID = L.LOCAL_CODE );

